"""
风控参数配置文件
"""

# 风控参数
MAX_SINGLE_POSITION_RATIO = 0.80      # 单只个股最大仓位（%总资产）
STOP_LOSS_AGGRESSIVE = 0.20           # 妖股硬止损线（7%亏损）
STOP_LOSS_GENTLE = 0.30               # 蓝筹软止损线（10%亏损）
PROFIT_TAKE_THRESHOLD = 0.50          # 止盈线（30%盈利）
BASE_POSITION_RATIO = 0.80            # 基础仓位比例（2%总资产）
MIN_ORDER_AMOUNT = 1               # 最低起买额（元）

# 执行层参数
MAX_DAILY_ORDERS = 10                 # 每日最大下单数
ORDER_EXPIRE_MINUTES = 15             # 挂单超时撤单（分钟）

# 优先级权重（用于扩展）
PRIORITY_URGENCY_WEIGHT = 0.6
PRIORITY_RISK_WEIGHT = 0.3
PRIORITY_TAG_WEIGHT = 0.1

# 默认配置字典
DEFAULT_RISK_CONFIG = {
    'MAX_SINGLE_POSITION_RATIO': MAX_SINGLE_POSITION_RATIO,
    'STOP_LOSS_AGGRESSIVE': STOP_LOSS_AGGRESSIVE,
    'STOP_LOSS_GENTLE': STOP_LOSS_GENTLE,
    'PROFIT_TAKE_THRESHOLD': PROFIT_TAKE_THRESHOLD,
    'BASE_POSITION_RATIO': BASE_POSITION_RATIO,
    'MIN_ORDER_AMOUNT': MIN_ORDER_AMOUNT,
    'MAX_DAILY_ORDERS': MAX_DAILY_ORDERS,
    'ORDER_EXPIRE_MINUTES': ORDER_EXPIRE_MINUTES,
}


# 死区参数（评分接近0时不交易）
DEAD_ZONE = 0.001
MIN_POSITION_RATIO = 0.02  # 最小仓位比例 2%

# 更新默认配置字典
DEFAULT_RISK_CONFIG.update({
    'DEAD_ZONE': DEAD_ZONE,
    'MIN_POSITION_RATIO': MIN_POSITION_RATIO,
})


EARLY_SCORE_THRESHOLD = 0.015
EARLY_SCORE_MAGNITUDE = 2.0
EARLY_SCORE_NEUTRAL = 0.5
